CREATE TYPE "gender_type" AS ENUM (
  'male',
  'female'
);

CREATE TYPE "notification_type" AS ENUM (
  'system_alert',
  'achievement',
  'content_update'
);

CREATE TYPE "activity_level" AS ENUM (
  'sedentary',
  'lightly_active',
  'moderately_active',
  'very_active'
);

CREATE TYPE "meal_type" AS ENUM (
  'breakfast',
  'lunch',
  'dinner',
  'snack'
);

CREATE TYPE "content_type" AS ENUM (
  'article',
  'video'
);

CREATE TYPE "food_type" AS ENUM (
  'raw_ingredient',
  'recipe_dish'
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "username" varchar,
  "gender" gender_type,
  "birth_date" date,
  "height_cm" decimal(5,2),
  "current_weight_kg" decimal(5,2),
  "activity_level" activity_level,
  "target_weight_kg" decimal(5,2),
  "target_calories" int,
  "current_streak" int DEFAULT 0,
  "last_login_date" date,
  "total_login_days" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "notification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "title" varchar NOT NULL,
  "message" text,
  "type" notification_type,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "foods" (
  "food_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "type" food_type DEFAULT 'raw_ingredient',
  "calories" decimal(6,2),
  "protein" decimal(6,2),
  "carbs" decimal(6,2),
  "fat" decimal(6,2),
  "sodium" decimal(6,2),
  "sugar" decimal(6,2),
  "image_url" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "recipes" (
  "recipe_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "food_id" bigint NOT NULL,
  "description" varchar,
  "instructions" text,
  "prep_time_minutes" int DEFAULT 0,
  "cooking_time_minutes" int DEFAULT 0,
  "serving_people" decimal(3,1) DEFAULT 1,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "recipe_ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipe_id" bigint NOT NULL,
  "ingredient_food_id" bigint NOT NULL,
  "amount" decimal(6,2),
  "unit_id" int NOT NULL
);

CREATE TABLE "units" (
  "unit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "weight_logs" (
  "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "weight_kg" decimal(5,2),
  "recorded_date" date DEFAULT (now())
);

CREATE TABLE "food_logs" (
  "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "food_id" bigint,
  "date_consumed" date DEFAULT (now()),
  "meal_type" meal_type,
  "amount_consumed" decimal(4,2),
  "logged_calories" decimal(6,2)
);

CREATE TABLE "daily_summaries" (
  "summary_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "date_record" date,
  "water_intake_glasses" int DEFAULT 0,
  "total_calories_intake" decimal(6,2)
);

CREATE TABLE "health_contents" (
  "content_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "type" content_type,
  "thumbnail_url" varchar,
  "resource_url" varchar,
  "description" text,
  "is_published" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "achievements" (
  "achievement_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "icon_url" varchar,
  "criteria_type" varchar,
  "criteria_value" int
);

CREATE TABLE "user_achievements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "achievement_id" int,
  "earned_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "users"."current_streak" IS 'จำนวนวันที่ใช้งานต่อเนื่องล่าสุด';

COMMENT ON COLUMN "users"."last_login_date" IS 'วันที่เข้าใช้งานล่าสุด เอาไว้เช็คว่า streak ขาดไหม';

COMMENT ON COLUMN "users"."total_login_days" IS 'ล็อกอินรวมกี่วันแล้ว (Lifetime)';

COMMENT ON COLUMN "notifications"."title" IS 'หัวข้อ เช่น "อย่าลืมกินข้าวนะ"';

COMMENT ON COLUMN "notifications"."message" IS 'รายละเอียด';

COMMENT ON COLUMN "notifications"."is_read" IS 'อ่านหรือยัง?';

COMMENT ON COLUMN "recipes"."food_id" IS 'สูตรนี้ทำแล้วได้อาหารจานไหน? (1-to-1)';

COMMENT ON COLUMN "recipes"."description" IS 'คำบรรยายสั้นๆ';

COMMENT ON COLUMN "recipes"."instructions" IS 'วิธีทำ: 1. ตั้งหม้อ... 2. ใส่หมู...';

COMMENT ON COLUMN "recipes"."serving_people" IS 'สูตรนี้กินได้กี่คน? (เอาไว้หาร)';

COMMENT ON COLUMN "recipe_ingredients"."amount" IS 'ปริมาณที่ใช้';

COMMENT ON COLUMN "health_contents"."thumbnail_url" IS 'รูปปกคลิป/รูปหัวข้อ';

COMMENT ON COLUMN "health_contents"."resource_url" IS 'ลิงก์ไป YouTube หรือ URL บทความ';

COMMENT ON COLUMN "achievements"."name" IS 'เช่น "นักลดน้ำหนักมือใหม่"';

COMMENT ON COLUMN "achievements"."icon_url" IS 'รูปเหรียญรางวัล';

COMMENT ON COLUMN "achievements"."criteria_type" IS 'เช่น login_streak, weight_lost';

COMMENT ON COLUMN "achievements"."criteria_value" IS 'เช่น 7 (วัน), 1 (กก.)';

COMMENT ON COLUMN "user_achievements"."earned_at" IS 'ได้รางวัลเมื่อไหร่';

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("recipe_id");

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("ingredient_food_id") REFERENCES "foods" ("food_id");

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("unit_id");

ALTER TABLE "weight_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "food_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "food_logs" ADD FOREIGN KEY ("food_id") REFERENCES "foods" ("food_id");

ALTER TABLE "daily_summaries" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("achievement_id");
