CREATE TYPE "verification_status" AS ENUM (
  'pending',
  'verified',
  'rejected'
);

CREATE TYPE "data_source" AS ENUM (
  'user_created',
  'system_calculation',
  'official_db'
);

CREATE TYPE "food_type" AS ENUM (
  'raw_ingredient',
  'brand_product',
  'recipe'
);

CREATE TYPE "meal_type" AS ENUM (
  'breakfast',
  'lunch',
  'dinner',
  'snack'
);

CREATE TYPE "gender_type" AS ENUM (
  'M',
  'F'
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "birth_date" date,
  "gender" gender_type,
  "height_cm" decimal(5,2),
  "weight_kg" decimal(5,2),
  "activity_level" decimal(3,2),
  "BMI" decimal(3,2),
  "TDEE" decimal(3,2),
  "goals" int,
  "Due_date" date,
  "User_is_active" boolean DEFAULT true,
  "last_login_at" timestamp,
  "progress_id" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "foods" (
  "Food_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Food_name" varchar NOT NULL,
  "type" food_type NOT NULL,
  "calories" decimal(6,2) DEFAULT 0,
  "protein" decimal(6,2) DEFAULT 0,
  "carbs" decimal(6,2) DEFAULT 0,
  "fat" decimal(6,2) DEFAULT 0,
  "sodium_mg" decimal(6,2),
  "fiber_g" decimal(6,2),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "units" (
  "unit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "food_portions" (
  "portion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Food_id" bigint NOT NULL,
  "unit_id" int NOT NULL,
  "gram_weight" decimal(6,2) NOT NULL,
  "description" varchar
);

CREATE TABLE "recipe_ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_food_id" bigint NOT NULL,
  "ingredient_food_id" bigint NOT NULL,
  "amount" decimal(6,2),
  "unit_id" int NOT NULL,
  "yield_percentage" decimal(5,2) DEFAULT 100
);

CREATE TABLE "daily_logs" (
  "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "date_consumed" date DEFAULT (now()),
  "meal_type" meal_type,
  "food_id" bigint NOT NULL,
  "amount_consumed" decimal(6,2),
  "unit_id" int NOT NULL,
  "logged_calories" decimal(6,2),
  "logged_protein" decimal(6,2),
  "logged_carbs" decimal(6,2),
  "logged_fat" decimal(6,2),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "Progress" (
  "progress_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Due_date" date,
  "success_goal_date" date,
  "Streak_date" date,
  "Weight_kg" decimal(5,2),
  "Goal_Weight_kg" decimal(5,2)
);

CREATE TABLE "Daily_Data_record" (
  "Activity" varchar(50),
  "Daily_Food" varchar(50)
);

COMMENT ON COLUMN "users"."User_is_active" IS 'สถานะบัญชี';

COMMENT ON COLUMN "users"."updated_at" IS 'แก้ไข Profile ล่าสุดเมื่อไหร่';

COMMENT ON COLUMN "units"."name" IS 'e.g., g, kg, tbsp, cup';

COMMENT ON COLUMN "daily_logs"."updated_at" IS 'กรณี User มาแก้ไข log ย้อนหลัง';

ALTER TABLE "food_portions" ADD FOREIGN KEY ("Food_id") REFERENCES "foods" ("Food_id");

ALTER TABLE "food_portions" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("unit_id");

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("parent_food_id") REFERENCES "foods" ("Food_id");

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("ingredient_food_id") REFERENCES "foods" ("Food_id");

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("unit_id");

ALTER TABLE "daily_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "daily_logs" ADD FOREIGN KEY ("food_id") REFERENCES "foods" ("Food_id");

ALTER TABLE "daily_logs" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("unit_id");

ALTER TABLE "Progress" ADD FOREIGN KEY ("progress_id") REFERENCES "users" ("progress_id");
