// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr3HnopKTDymwC0Sr4XvcP8e2n_vAtIas',
    appId: '1:523714837784:web:ca02d376cbd13b7036726d',
    messagingSenderId: '523714837784',
    projectId: 'calguard-project',
    authDomain: 'calguard-project.firebaseapp.com',
    storageBucket: 'calguard-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxb20G7I3ptX7URRBw6WCzBaQVYZCp0I',
    appId: '1:523714837784:android:a4feaffc195916c836726d',
    messagingSenderId: '523714837784',
    projectId: 'calguard-project',
    storageBucket: 'calguard-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmzXNcQxZ7zbZqCw_-t1h7f1-XiqHs5fc',
    appId: '1:523714837784:ios:bd0dbc57776c939d36726d',
    messagingSenderId: '523714837784',
    projectId: 'calguard-project',
    storageBucket: 'calguard-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmzXNcQxZ7zbZqCw_-t1h7f1-XiqHs5fc',
    appId: '1:523714837784:ios:bd0dbc57776c939d36726d',
    messagingSenderId: '523714837784',
    projectId: 'calguard-project',
    storageBucket: 'calguard-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr3HnopKTDymwC0Sr4XvcP8e2n_vAtIas',
    appId: '1:523714837784:web:cbb572c38b49514036726d',
    messagingSenderId: '523714837784',
    projectId: 'calguard-project',
    authDomain: 'calguard-project.firebaseapp.com',
    storageBucket: 'calguard-project.firebasestorage.app',
  );
}
